import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { compile } from 'tailwindcss';

const require = createRequire(import.meta.url);
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const sourceExtensions = new Set(['.tsx', '.ts', '.html']);
const sourceFiles = [];

function walk(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === '.git' || entry.name === 'node_modules' || entry.name === 'dist') continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full);
    else if (sourceExtensions.has(path.extname(entry.name))) sourceFiles.push(full);
  }
}

walk(root);

const candidates = new Set();
const literalPatterns = [
  /'((?:\\.|[^'\\])*)'/g,
  /"((?:\\.|[^"\\])*)"/g,
  /`((?:\\.|[^`\\])*)`/g,
];

function collectCandidates(text, pattern) {
  pattern.lastIndex = 0;
  let match;
  while ((match = pattern.exec(text))) {
    for (let token of match[1].split(/\s+/)) {
      token = token.trim().replace(/^[{(<,;]+|[})>,;]+$/g, '').replace(/^["']+|["']+$/g, '');
      if (!token || token.includes('${') || token.length > 140) continue;
      candidates.add(token);
    }
  }
}

for (const file of sourceFiles) {
  const text = fs.readFileSync(file, 'utf8');
  // Scan quote styles independently. This deliberately sees quoted class alternatives nested
  // inside template literals, e.g. `${active ? 'bg-cyan-500' : 'bg-gray-900'}`.
  for (const pattern of literalPatterns) collectCandidates(text, pattern);
}

const tailwindSourcePath = require.resolve('tailwindcss/index.css');
const tailwindSource = fs.readFileSync(tailwindSourcePath, 'utf8');
const compiler = await compile(tailwindSource);
const generated = compiler.build([...candidates].sort());
const shell = `\n/* Application shell. */\nhtml, body, #root { margin: 0; width: 100%; height: 100%; overflow: hidden; background: #030712; }\nbody { overscroll-behavior: none; }\n`;
const header = '/* Generated by scripts/build-styles.mjs. Do not hand-edit. */\n';
fs.writeFileSync(path.join(root, 'styles.css'), header + generated + shell);
console.log(`Generated styles.css from ${sourceFiles.length} source files and ${candidates.size} candidate tokens.`);
